# repos:
#   # Ruff for Python linting
#   - repo: https://github.com/charliermarsh/ruff-pre-commit
#     rev: v0.47.0  # Use the latest version here
#     hooks:
#       - id: ruff
#         args: ["--max-line-length=100"]

#   # SQLFluff for SQL linting
#   - repo: https://github.com/sqlfluff/sqlfluff
#     rev: 1.6.0  # Use the latest version here
#     hooks:
#       - id: sqlfluff-lint
#         name: sqlfluff lint
#         entry: sqlfluff lint
#         args: ["--dialect", "snowflake", "--templater", "dbt"]
#         language: python
#         types: [sql]
#       - id: sqlfluff-fix
#         name: sqlfluff fix
#         entry: sqlfluff fix
#         args: ["--dialect", "snowflake", "--templater", "dbt"]
#         language: python
#         types: [sql]
        
#   # Check for trailing whitespace and end-of-file consistency
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.3.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
